import type { Card, Decklist } from "./types";

export const decklistsData: Decklist[] = [
  { id: 1, cardName: "Archfiend",  duelist: "Chuong", title: "Archfiend Variant 1", image: "/decklist/archfiend.PNG" },
  { id: 2, cardName: "Phantasm Spiral",  duelist: "Chuong", title: "Phantasm Spiral Variant 1", image: "/decklist/phantasmSpiral.PNG" },
  { id: 3, cardName: "Dark Magician",  duelist: "Chuong", title: "Dark Magician Variant 1", image: "/decklist/darkMagician.PNG" },
  { id: 4, cardName: "Dark Magician",  duelist: "Chuong", title: "Dark Magician Variant 2", image: "/decklist/darkMagician2.PNG" },
  { id: 5, cardName: "Eldlich",  duelist: "Chuong", title: "Eldlich Variant 1", image: "/decklist/eldlich.PNG" },
  { id: 6, cardName: "Eldlich",  duelist: "Chuong", title: "Eldlich Variant 2", image: "/decklist/eldlich2.PNG" },
];

export const cardsData: Card[] = [
  { id: 1, name: "Ancient Warriors", level: 6, rarity: "rare", locked: false, image: "/cards/ancientWarriors.jpg", duelist: "Chuong" },
  { id: 2, name: "Apophis", level: 7, rarity: "epic", locked: false, image: "/cards/apophis.jpg", duelist: "Chuong" },
  { id: 3, name: "Arcana Force", level: 4, rarity: "common", locked: false, image: "/cards/arcanaForce.jpg", duelist: "Chuong" },
  { id: 4, name: "Archfiend", level: 7, rarity: "rare", locked: false, image: "/cards/archfiend.jpg", duelist: "Chuong" },
  { id: 5, name: "Assault Mode", level: 6, rarity: "rare", locked: false, image: "/cards/assaultMode.jpg", duelist: "Chuong" },
  { id: 6, name: "Buster Blader", level: 6, rarity: "rare", locked: false, image: "/cards/busterBlader.jpg", duelist: "Chuong" },
  { id: 7, name: "Dark Magician", level: 6, rarity: "rare", locked: false, image: "/cards/darkMagician.jpg", duelist: "Chuong" },
  { id: 8, name: "Eldlich", level: 6, rarity: "rare", locked: false, image: "/cards/eldlich.jpg", duelist: "Chuong" },
  { id: 9, name: "Evil Eye", level: 6, rarity: "rare", locked: false, image: "/cards/evilEye.jpg", duelist: "Chuong" },
  { id: 10, name: "Fabled", level: 5, rarity: "rare", locked: false, image: "/cards/fabled.jpg", duelist: "Chuong" },
  { id: 11, name: "Flame Swordsman", level: 6, rarity: "rare", locked: false, image: "/cards/flameSwordman.jpg", duelist: "Chuong" },
  { id: 12, name: "Fur Hire", level: 7, rarity: "epic", locked: false, image: "/cards/furHire.jpg", duelist: "Chuong" },
  { id: 13, name: "Gate Guardian", level: 5, rarity: "rare", locked: false, image: "/cards/gateGuardian.jpg", duelist: "Chuong" },
  { id: 14, name: "Gem-Knight", level: 7, rarity: "epic", locked: false, image: "/cards/gemKnight.jpg", duelist: "Chuong" },
  { id: 15, name: "Ghoti", level: 6, rarity: "rare", locked: false, image: "/cards/ghoti.jpg", duelist: "Chuong" },
  { id: 16, name: "Icejade", level: 5, rarity: "rare", locked: false, image: "/cards/icejade.jpg", duelist: "Chuong" },
  { id: 17, name: "Infernoble Knight", level: 6, rarity: "rare", locked: false, image: "/cards/infernobleKnight.jpg", duelist: "Chuong" },
  { id: 18, name: "Libromancer", level: 5, rarity: "rare", locked: false, image: "/cards/libromancer.jpg", duelist: "Chuong" },
  { id: 19, name: "Madolche", level: 6, rarity: "rare", locked: false, image: "/cards/madolche.jpg", duelist: "Chuong" },
  { id: 20, name: "Majespecter", level: 6, rarity: "rare", locked: false, image: "/cards/majespecter.jpg", duelist: "Chuong" },
  { id: 21, name: "Materiactor", level: 6, rarity: "rare", locked: false, image: "/cards/materiactor.jpg", duelist: "Chuong" },
  { id: 22, name: "Megalith", level: 6, rarity: "rare", locked: false, image: "/cards/megalith.jpg", duelist: "Chuong" },
  { id: 23, name: "Memento", level: 8, rarity: "epic", locked: false, image: "/cards/memento.jpg", duelist: "Chuong" },
  { id: 24, name: "Mikanko", level: 7, rarity: "epic", locked: false, image: "/cards/mikanko.jpg", duelist: "Chuong" },
  { id: 25, name: "Mimighoul", level: 6, rarity: "rare", locked: false, image: "/cards/mimighoul.jpg", duelist: "Chuong" },
  { id: 26, name: "Monarch", level: 7, rarity: "epic", locked: false, image: "/cards/monarch.jpg", duelist: "Chuong" },
  { id: 27, name: "Morganite", level: 7, rarity: "epic", locked: false, image: "/cards/morganite.jpg", duelist: "Chuong" },
  { id: 28, name: "Nemleria", level: 7, rarity: "epic", locked: false, image: "/cards/nemleria.png", duelist: "Chuong" },
  { id: 29, name: "Ninja", level: 6, rarity: "rare", locked: false, image: "/cards/ninja.jpg", duelist: "Chuong" },
  { id: 30, name: "P.U.N.K", level: 7, rarity: "epic", locked: false, image: "/cards/p.u.n.k.jpg", duelist: "Chuong" },
  { id: 31, name: "Phantasm Spiral", level: 7, rarity: "epic", locked: false, image: "/cards/phantasmSpiral.jpg", duelist: "Chuong" },
  { id: 32, name: "Predaplant", level: 8, rarity: "epic", locked: false, image: "/cards/predaplant.jpg", duelist: "Chuong" },
  { id: 33, name: "Radiant Typhoon", level: 9, rarity: "legendary", locked: false, image: "/cards/radiantTyphoon.jpg", duelist: "Chuong" },
  { id: 34, name: "Regenesis", level: 7, rarity: "epic", locked: false, image: "/cards/regenesis.jpg", duelist: "Chuong" },
  { id: 35, name: "Rose Dragon", level: 7, rarity: "epic", locked: false, image: "/cards/roseDragon.jpg", duelist: "Chuong" },
  { id: 36, name: "Shining Sarcophagus", level: 7, rarity: "epic", locked: false, image: "/cards/shiningSarcophagus.jpg", duelist: "Chuong" },
  { id: 37, name: "Skull Servant", level: 6, rarity: "rare", locked: false, image: "/cards/skullServant.jpg", duelist: "Chuong" },
  { id: 38, name: "Spright", level: 6, rarity: "rare", locked: false, image: "/cards/spright.jpeg", duelist: "Chuong" },
  { id: 39, name: "Springans", level: 6, rarity: "rare", locked: false, image: "/cards/springans.jpg", duelist: "Chuong" },
  { id: 40, name: "Spyral", level: 6, rarity: "rare", locked: false, image: "/cards/spyral.jpg", duelist: "Chuong" },
  { id: 41, name: "Tistina", level: 7, rarity: "epic", locked: false, image: "/cards/tistina.jpg", duelist: "Chuong" },
  { id: 42, name: "Train", level: 7, rarity: "epic", locked: false, image: "/cards/train.jpg", duelist: "Chuong" },
  { id: 43, name: "Tri-Brigade", level: 6, rarity: "rare", locked: false, image: "/cards/tri-brigade.jpg", duelist: "Chuong" },
  { id: 44, name: "Weather Painter", level: 7, rarity: "epic", locked: false, image: "/cards/weatherPainter.jpg", duelist: "Chuong" },
  { id: 45, name: "Witchcrafter", level: 6, rarity: "rare", locked: false, image: "/cards/witchcrafter.jpg", duelist: "Chuong" },
  { id: 46, name: "Magical Musketeer", level: 7, rarity: "epic", locked: false, image: "/cards/magicalMusketeer.jpg", duelist: "Chuong" },
  { id: 47, name: "Floowandereeze", level: 7, rarity: "epic", locked: false, image: "/cards/floowandereeze.jpg", duelist: "Bao" },
  { id: 48, name: "Voiceless Voice", level: 7, rarity: "epic", locked: false, image: "/cards/voicelessVoice.jpg", duelist: "Bao" },
  { id: 49, name: "Exosisters", level: 7, rarity: "epic", locked: false, image: "/cards/exosisters.jpg", duelist: "Bao" },
  { id: 50, name: "k9", level: 9, rarity: "legendary", locked: false, image: "/cards/k9-1.jpg", duelist: "Bao" },
  { id: 51, name: "Yummy", level: 8, rarity: "epic", locked: false, image: "/cards/yummy-1.jpg", duelist: "Bao" },
  { id: 52, name: "Hecahands", level: 7, rarity: "rare", locked: false, image: "/cards/hecahands.jpg", duelist: "Bao" },
  { id: 53, name: "Salamangreat", level: 7, rarity: "epic", locked: false, image: "/cards/salamangreat.jpg", duelist: "BaoCyberse" },
  { id: 54, name: "Maliss", level: 9, rarity: "legendary", locked: false, image: "/cards/maliss.jpg", duelist: "BaoCyberse" },
  { id: 55, name: "Marincess", level: 5, rarity: "rare", locked: false, image: "/cards/marincess.jpg", duelist: "BaoCyberse" },
  { id: 56, name: "Math Mech", level: 6, rarity: "rare", locked: false, image: "/cards/mathMech.jpg", duelist: "BaoCyberse" },
  { id: 57, name: "Vaylantz", level: 6, rarity: "rare", locked: false, image: "/cards/vaylantz.jpg", duelist: "BaoCyberse" },
  { id: 58, name: "Memento", level: 8, rarity: "epic", locked: false, image: "/cards/memento.jpg", duelist: "BaoCyberse" },
  { id: 59, name: "Goblin Biker", level: 7, rarity: "epic", locked: false, image: "/cards/goblinBiker.jpg", duelist: "BaoCyberse" },
  { id: 60, name: "Ignister", level: 8, rarity: "epic", locked: false, image: "/cards/ignister.jpg", duelist: "BaoCyberse" },
  { id: 61, name: "Evil Twin", level: 7, rarity: "epic", locked: false, image: "/cards/evilTwin.jpg", duelist: "BaoCyberse" },
  { id: 62, name: "Rikka", level: 7, rarity: "epic", locked: false, image: "/cards/rikka.jpg", duelist: "Thach" },
  { id: 63, name: "Rose Dragon", level: 7, rarity: "epic", locked: false, image: "/cards/roseDragon.jpg", duelist: "Thach" },
  { id: 64, name: "Dark World", level: 6, rarity: "rare", locked: false, image: "/cards/darkWorld.jpg", duelist: "Duong" },
  { id: 65, name: "Red-eyes", level: 6, rarity: "rare", locked: false, image: "/cards/redEyes-1.jpg", duelist: "Duong" },
  { id: 66, name: "Shining Sarcophagus", level: 7, rarity: "epic", locked: false, image: "/cards/shiningSarcophagus.jpg", duelist: "Duong" },
  { id: 67, name: "Gimmick Puppet", level: 9, rarity: "legendary", locked: false, image: "/cards/gimmickPuppet.jpg", duelist: "Duong" },
  { id: 68, name: "Millennium", level: 9, rarity: "legendary", locked: false, image: "/cards/millennium.jpg", duelist:"Duong" },
  { id: 69, name: "Labrynth", level: 7, rarity: "epic", locked: false, image: "/cards/labrynth.jpg", duelist:"Ca" },
  { id: 70, name: "Sky Striker", level: 9, rarity: "legendary", locked: false, image: "/cards/skyStriker.jpg", duelist: "Ca" },
  { id: 71, name: "X-saber", level: 6, rarity: "rare", locked: false, image: "/cards/x-saber.jpg", duelist: "Tam" },
  { id: 72, name: "HERO", level: 8, rarity: "epic", locked: false, image: "/cards/hero.jpg", duelist: "Tam" },
  { id: 73, name: "Enneacraft", level: 8, rarity: "epic", locked: false, image: "/cards/enneacraft.jpg", duelist:"Tam" },
  { id: 74, name: "Shark", level: 7, rarity: "epic", locked: false, image: "/cards/shark.jpg", duelist: "Tam" },
  { id: 75, name: "Onomatopoeia", level: 7, rarity: "epic", locked: false, image: "/cards/onomatopoeia.jpg", duelist: "Tam" },
  { id: 76, name: "Mitsurugi", level: 10, rarity: "legendary", locked: false, image: "/cards/mitsurugi.jpg", duelist:"Tam" },
  { id: 77, name: "Megalith", level: 6, rarity: "rare", locked: false, image: "/cards/megalith.jpg", duelist: "Tam" },
  { id: 78, name: "Doom-z", level: 7, rarity: "epic", locked: false, image: "/cards/doomz.jpg", duelist:"Tam" },
  { id: 79, name: "Dark Lord", level: 8, rarity: "epic", locked: false, image: "/cards/darklord.jpg", duelist: "Tam" },
  { id: 80, name: "Blue-eyes", level: 8, rarity: "epic", locked: false, image: "/cards/blueEyes.jpg", duelist: "Tam" },
  { id: 81, name: "Plunder Patrol", level: 7, rarity: "epic", locked: false, image: "/cards/plunderPatrol.jpg", duelist: "Toan" },
  { id: 82, name: "Magnet Warrior", level: 9, rarity: "legendary", locked: false, image: "/cards/magnetWarrior.jpg", duelist: "Toan" },
  { id: 83, name: "Crystal Beast", level: 7, rarity: "epic", locked: false, image: "/cards/crystalBeast.jpg", duelist: "Toan" },
  { id: 84, name: "Gladiator Beast", level: 7, rarity: "epic", locked: false, image: "/cards/gladiatorBeast.jpg", duelist:"Toan" },
  { id: 85, name: "Paleozoic", level: 7, rarity: "epic", locked: false, image: "/cards/paleozoic.jpg", duelist:"Toan" },
  { id: 86, name: "Volcanic", level: 4, rarity: "common", locked: false, image: "/cards/volcanic.jpg", duelist:"Toan" },
  { id: 87, name: "Ursarctic", level: 4, rarity: "common", locked: false, image: "/cards/ursarctic.jpg", duelist:"Toan" },
  { id: 88, name: "P.U.N.K", level: 7, rarity: "epic", locked: false, image: "/cards/p.u.n.k.jpg", duelist:"Phuc" },
  { id: 89, name: "Salamangreat", level: 7, rarity: "epic", locked: false, image: "/cards/salamangreat.jpg", duelist:"Phuc" },
  { id: 90, name: "Atlantean", level: 7, rarity: "epic", locked: false, image: "/cards/atlantean.jpg", duelist:"Phuc" },
  { id: 91, name: "Ancient Gear", level: 6, rarity: "rare", locked: false, image: "/cards/ancientGear.jpg", duelist:"Phuc" },
  { id: 92, name: "Burning Abyss", level: 6, rarity: "rare", locked: false, image: "/cards/burningAbyss.jpg", duelist:"Phuc" },
  { id: 93, name: "Infernoid", level: 7, rarity: "epic", locked: false, image: "/cards/infernoid.jpg", duelist:"Phuc" },
  { id: 94, name: "Exosister", level: 7, rarity: "epic", locked: false, image: "/cards/exosisters.jpg", duelist:"Phuc" },
  { id: 95, name: "Phantom Knight", level: 6, rarity: "rare", locked: false, image: "/cards/phantomKnight.jpg", duelist:"Phuc" },
  { id: 96, name: "Altergeist", level: 6, rarity: "rare", locked: false, image: "/cards/altergeist.png", duelist:"Phuc" },
  { id: 97, name: "Fire King", level: 8, rarity: "epic", locked: false, image: "/cards/fireKing.jpg", duelist:"Phuc" },
  { id: 98, name: "Dracotail", level: 9, rarity: "legendary", locked: false, image: "/cards/dracotailBranded.jpg", duelist:"Fake" },
  { id: 99, name: "D/D/D", level: 8, rarity: "legendary", locked: false, image: "/cards/ddd.jpg", duelist:"Fake" },
  { id: 100, name: "Atlantean", level: 7, rarity: "epic", locked: false, image: "/cards/atlantean.jpg", duelist:"Fake" },
  { id: 101, name: "Branded", level: 9, rarity: "legendary", locked: false, image: "/cards/branded.jpg", duelist:"Fake" },
  { id: 102, name: "Purrely", level: 7, rarity: "epic", locked: false, image: "/cards/purrely.jpg", duelist:"Fake" },
  { id: 103, name: "Swordsoul", level: 7, rarity: "epic", locked: false, image: "/cards/swordsoul.jpg", duelist:"Fake" },
  { id: 104, name: "Battlewasp", level: 6, rarity: "rare", locked: false, image: "/cards/battlewasp.jpg", duelist:"Fake" },
  { id: 105, name: "Shaddoll", level: 7, rarity: "rare", locked: false, image: "/cards/shaddoll.jpg", duelist:"Fake" },
  { id: 106, name: "Ogdoabyss", level: 6, rarity: "rare", locked: false, image: "/cards/ogdoabyss.jpg", duelist:"Fake" },
  { id: 107, name: "Exosister", level: 7, rarity: "epic", locked: false, image: "/cards/exosisters.jpg", duelist:"An" },
  { id: 108, name: "White Forest", level: 7, rarity: "epic", locked: false, image: "/cards/whiteForest.jpg", duelist:"An" },
  { id: 109, name: "Rescue-Ace", level: 7, rarity: "epic", locked: false, image: "/cards/rescueAce.jpg", duelist:"An" },
  { id: 110, name: "Dracotail", level: 9, rarity: "legendary", locked: false, image: "/cards/dracotail.jpg", duelist:"An" },
  { id: 111, name: "Clown Clan", level: 9, rarity: "legendary", locked: false, image: "/cards/clownClan.jpg", duelist:"Duy" },
  { id: 112, name: "Vanquish Soul", level: 9, rarity: "legendary", locked: false, image: "/cards/vanquishSoul.jpg", duelist:"Duy" },
  { id: 113, name: "Yummy", level: 8, rarity: "legendary", locked: false, image: "/cards/yummy-2.jpg", duelist:"Du" },
  { id: 114, name: "Lunalight", level: 8, rarity: "epic", locked: false, image: "/cards/lunalight-1.jpg", duelist:"Du" },
  { id: 115, name: "Lunalight", level: 8, rarity: "epic", locked: false, image: "/cards/lunalight-2.jpg", duelist:"Tai" },
  { id: 116, name: "Yummy", level: 8, rarity: "epic", locked: false, image: "/cards/yummy-3.jpg", duelist:"Tai" },
  { id: 117, name: "Super Quantal", level: 7, rarity: "epic", locked: false, image: "/cards/superQuantal.jpg", duelist:"Tai" },
  { id: 118, name: "Elfnote", level: 10, rarity: "legendary", locked: false, image: "/cards/elfnote.jpg", duelist: "Thanh" },
  { id: 119, name: "Six Samurai", level: 7, rarity: "epic", locked: false, image: "/cards/sixSamurai.jpg", duelist: "Thanh" },
  { id: 120, name: "Dark World", level: 6, rarity: "rare", locked: false, image: "/cards/darkWorld.jpg", duelist: "Thanh" },
  { id: 121, name: "Rokket", level: 8, rarity: "epic", locked: false, image: "/cards/rokket.jpg", duelist: "Thanh" },
  { id: 122, name: "Dragunity", level: 7, rarity: "epic", locked: false, image: "/cards/dragunity.jpg", duelist: "Thanh" },
  { id: 123, name: "Dragonmaid", level: 7, rarity: "rare", locked: false, image: "/cards/dragonmaid.jpg", duelist: "Thanh" },
  { id: 124, name: "Vanquish Soul", level: 9, rarity: "legendary", locked: false, image: "/cards/vanquishSoul.jpg", duelist: "Thanh" },
  { id: 125, name: "Speedroid", level: 6, rarity: "rare", locked: false, image: "/cards/speedroid.jpg", duelist: "Thanh" },
  { id: 126, name: "Red Dragon Archfiend", level: 7, rarity: "epic", locked: false, image: "/cards/redDragonArchfiend.jpg", duelist: "Thanh" },
  { id: 127, name: "Dark Lord", level: 8, rarity: "epic", locked: false, image: "/cards/darklord.jpg", duelist: "Thanh" },
  { id: 128, name: "Tellarknight", level: 9, rarity: "legendary", locked: false, image: "/cards/tellarknight.jpg", duelist: "Thanh" },
  { id: 129, name: "White Forest", level: 8, rarity: "epic", locked: false, image: "/cards/whiteForest.jpg", duelist: "Thanh" },
  { id: 130, name: "Floowandereeze", level: 8, rarity: "epic", locked: false, image: "/cards/floowandereeze.jpg", duelist: "Thanh" },
  { id: 131, name: "Swordsoul", level: 7, rarity: "epic", locked: false, image: "/cards/swordsoul.jpg", duelist: "Thanh" },
  { id: 132, name: "Raidraptor", level: 7, rarity: "epic", locked: false, image: "/cards/raidraptor.jpg", duelist:"Thanh" },
  { id: 133, name: "Raidraptor", level: 7, rarity: "epic", locked: false, image: "/cards/raidraptor.jpg", duelist:"Tam" },
  { id: 134, name: "Apophis", level: 8, rarity: "epic", locked: false, image: "/cards/apophis.jpg", duelist:"Thanh" },
  { id: 135, name: "Doom Z", level: 8, rarity: "epic", locked: false, image: "/cards/doomz.jpg", duelist:"Thanh" },
  { id: 136, name: "Artmage", level: 8, rarity: "epic", locked: false, image: "/cards/artmage.jpg", duelist:"Thanh" },
  { id: 137, name: "Orcust", level: 8, rarity: "epic", locked: false, image: "/cards/orcust.jpg", duelist:"Thanh" },
  { id: 138, name: "True Draco", level: 7, rarity: "epic", locked: false, image: "/cards/trueDraco.png", duelist:"Thanh" },
  { id: 139, name: "Dracotail", level: 9, rarity: "legendary", locked: false, image: "/cards/dracotail.jpg", duelist:"Duy" },

  { id: 140, name: "Simorgh", level: 6, rarity: "rare", locked: true, image: "/cards/simorgh.jpg", duelist: "Chuong Choice" },
  { id: 141, name: "Gaia", level: 7, rarity: "epic", locked: true, image: "/cards/gaia.jpg", duelist: "Chuong Choice" },
  { id: 142, name: "Black Luster Solder", level: 4, rarity: "common", locked: true, image: "/cards/bls.jpg", duelist: "Chuong Choice" },
  { id: 143, name: "Krawler", level: 7, rarity: "rare", locked: true, image: "/cards/krawler.jpg", duelist: "Chuong Choice" },
  { id: 144, name: "Earthbound", level: 6, rarity: "rare", locked: true, image: "/cards/earthbound.jpg", duelist: "Chuong Choice" },
  { id: 145, name: "Clear", level: 6, rarity: "rare", locked: true, image: "/cards/clear.jpg", duelist: "Chuong Choice" },
  { id: 146, name: "Yosenju", level: 6, rarity: "rare", locked: true, image: "/cards/yosenju.jpg", duelist: "Chuong Choice" },
  { id: 147, name: "Windwitch", level: 6, rarity: "rare", locked: true, image: "/cards/windwitch.jpg", duelist: "Chuong Choice" },
  { id: 148, name: "Laval", level: 6, rarity: "rare", locked: true, image: "/cards/laval.jpg", duelist: "Chuong Choice" },
  { id: 149, name: "Time Thief", level: 5, rarity: "rare", locked: true, image: "/cards/timeThief.jpg", duelist: "Chuong Choice" },
  { id: 150, name: "Nephthys", level: 6, rarity: "rare", locked: true, image: "/cards/nephthys.jpg", duelist: "Chuong Choice" },
  { id: 151, name: "Hazy Flame", level: 7, rarity: "epic", locked: true, image: "/cards/hazyFlame.jpg", duelist:"Chuong Choice" },
  { id: 152, name: "Fortune Lady", level: 5, rarity: "rare", locked: true, image: "/cards/fortuneLady.jpg", duelist:"Chuong Choice" },
  { id: 153, name: "Shinobird", level: 7, rarity: "epic", locked: true, image: "/cards/shinobird.jpg", duelist: "Chuong Choice" },
  { id: 154, name: "Penguin", level: 6, rarity: "rare", locked: true, image: "/cards/penguin.jpg", duelist: "Chuong Choice" },
  { id: 155, name: "Toon", level: 5, rarity: "rare", locked: true, image: "/cards/toon.jpg", duelist: "Chuong Choice" },
  { id: 156, name: "Psy-frame", level: 6, rarity: "rare", locked: true, image: "/cards/psy-frame.jpg", duelist: "Chuong Choice" },
  { id: 157, name: "Joker Knight", level: 5, rarity: "rare", locked: true, image: "/cards/jokerKnight.jpg", duelist:"Chuong Choice" },
  { id: 158, name: "Performage", level: 6, rarity: "rare", locked: true, image: "/cards/performage.jpg", duelist: "Chuong Choice" },
  { id: 159, name: "Sacred Beast", level: 6, rarity: "rare", locked: true, image: "/cards/sacredBeast.jpg", duelist: "Chuong Choice" },
  { id: 160, name: "Star Warrior", level: 6, rarity: "rare", locked: true, image: "/cards/starWarrior.jpg", duelist: "Chuong Choice" },
  { id: 161, name: "U.A", level: 6, rarity: "rare", locked: true, image: "/cards/u-a.jpg", duelist: "Chuong Choice" },
  { id: 162, name: "F.A", level: 8, rarity: "epic", locked: true, image: "/cards/f-a.jpg", duelist:"Chuong Choice" },
  { id: 163, name: "Batteryman", level: 7, rarity: "epic", locked: true, image: "/cards/batteryman.jpg", duelist:"Chuong Choice" },
  { id: 164, name: "Prediction Princess", level: 6, rarity: "rare", locked: true, image: "/cards/predictionPrincess.jpg", duelist: "Chuong Choice" },
  { id: 165, name: "Noble Knight", level: 7, rarity: "epic", locked: true, image: "/cards/nobleKnight.jpg", duelist: "Chuong Choice" },
  { id: 166, name: "Battlin Boxer", level: 7, rarity: "epic", locked: true, image: "/cards/battlinBoxer.jpg", duelist: "Chuong Choice" },
  { id: 167, name: "Heroic", level: 7, rarity: "epic", locked: true, image: "/cards/heroic.jpg", duelist: "Chuong Choice" },
  { id: 168, name: "Watt", level: 6, rarity: "rare", locked: true, image: "/cards/watt.jpg", duelist:"Chuong Choice" },
  { id: 169, name: "Vampire", level: 7, rarity: "epic", locked: true, image: "/cards/vampire.jpg", duelist: "Chuong Choice" },
  { id: 170, name: "Aqua Actress", level: 7, rarity: "epic", locked: true, image: "/cards/aquaActress.jpg", duelist: "Chuong Choice" },
  { id: 171, name: "Jinzo", level: 8, rarity: "epic", locked: true, image: "/cards/jinzo.jpg", duelist: "Chuong Choice" },
  { id: 172, name: "Amorphage", level: 7, rarity: "epic", locked: true, image: "/cards/amorphage.jpg", duelist: "Chuong Choice" },
  { id: 173, name: "Graydle", level: 9, rarity: "legendary", locked: true, image: "/cards/graydle.jpg", duelist: "Chuong Choice" },
  { id: 174, name: "Relinquished", level: 7, rarity: "epic", locked: true, image: "/cards/relinquished.jpg", duelist: "Chuong Choice" },
  { id: 175, name: "Mecha Phantom Beast", level: 7, rarity: "epic", locked: true, image: "/cards/mechaPhantomBeast.jpg", duelist: "Chuong Choice" },
  { id: 176, name: "Vendread", level: 7, rarity: "epic", locked: true, image: "/cards/vendread.jpg", duelist: "Chuong Choice" },
  { id: 177, name: "Triamid", level: 6, rarity: "rare", locked: true, image: "/cards/triamid.jpg", duelist: "Chuong Choice" },
  { id: 178, name: "Igknight", level: 6, rarity: "rare", locked: true, image: "/cards/igknight.jpg", duelist: "Chuong Choice" },
  { id: 179, name: "Allure Queen", level: 6, rarity: "rare", locked: true, image: "/cards/allureQueen.jpg", duelist: "Chuong Choice" },
  { id: 180, name: "Shiranui", level: 6, rarity: "rare", locked: true, image: "/cards/shiranui.jpg", duelist:"Chuong Choice" },
  { id: 181, name: "Metaphys", level: 7, rarity: "epic", locked: true, image: "/cards/metaphys.jpg", duelist:"Chuong Choice"},
  { id: 182, name: "Zombie World", level: 7, rarity: "epic", locked: true, image: "/cards/zombieWorld.jpg", duelist:"Chuong Choice" },
 ];